export const QUIZZES = [
  {
    id: 'Q001',
    tacticId: 'T005',
    difficulty: 'medium',
    roles: ['analyst', 'executive'],
    question: 'Which of the following is the clearest example of the F3 Positioning tactic?',
    options: [
      { text: 'A fraudster phishes a bank employee for credentials',                                                          correct: false, rationale: 'That is Initial Access, not Positioning.' },
      { text: 'A fraud ring builds 12 months of on-time credit history on synthetic identities before executing a bust-out',  correct: true,  rationale: 'Positioning covers the preparation period within a compromised environment — waiting, cultivating trust, and mimicking legitimate behavior before execution.' },
      { text: 'A stolen $2M wire is split across 5 mule accounts',                                                            correct: false, rationale: 'That is Monetization (layering), not Positioning.' },
      { text: 'An attacker spoofs a trusted vendor\'s email domain',                                                          correct: false, rationale: 'That is Resource Development, not Positioning.' },
    ],
  },
  {
    id: 'Q002',
    tacticId: 'T007',
    difficulty: 'easy',
    roles: ['analyst', 'teller', 'soc', 'executive'],
    question: 'In a cyber-enabled fraud case, what determines fund recovery rate most strongly?',
    options: [
      { text: 'The quality of the SAR narrative filed with FinCEN',         correct: false, rationale: 'SARs are important but do not drive direct recovery.' },
      { text: 'Time elapsed between Execution and response',                correct: true,  rationale: 'Recovery probability drops sharply after the first 60 minutes as layering (Monetization) proceeds. Speed matters more than any other factor.' },
      { text: 'The total dollar amount lost',                               correct: false, rationale: 'Size does not determine recoverability; speed and layering status do.' },
      { text: 'Whether the attacker used cryptocurrency',                   correct: false, rationale: 'Crypto makes recovery harder but responsiveness still matters more.' },
    ],
  },
  {
    id: 'Q003',
    tacticId: 'T003',
    difficulty: 'medium',
    roles: ['soc', 'analyst'],
    question: 'A customer\'s account shows: (1) new device login from a new country, (2) SMS MFA code delivery failing, (3) device fingerprint changed. Which F3 stage is most likely active?',
    options: [
      { text: 'Reconnaissance',         correct: false, rationale: 'Recon does not involve interacting with the target account.' },
      { text: 'Initial Access',         correct: true,  rationale: 'The pattern indicates an active account takeover attempt — likely following a SIM swap that enabled MFA bypass.' },
      { text: 'Positioning',            correct: false, rationale: 'Positioning is characterized by patient, legitimate-looking behavior.' },
      { text: 'Monetization',           correct: false, rationale: 'Monetization happens after the fraudulent transaction has been executed.' },
    ],
  },
  {
    id: 'Q004',
    tacticId: 'T006',
    difficulty: 'easy',
    roles: ['teller', 'analyst', 'executive'],
    question: 'A customer walks in demanding an urgent wire based on "an email from the CFO." Which control is the single best defense?',
    options: [
      { text: 'Require a printed copy of the email',                         correct: false, rationale: 'Email is trivial to print — this adds no security.' },
      { text: 'Call the CFO on a pre-established, known phone number',       correct: true,  rationale: 'Out-of-band verification via a known channel defeats BEC entirely. The attacker controls the email but not the phone line.' },
      { text: 'Require the email be forwarded to compliance',                correct: false, rationale: 'Compliance review without out-of-band contact can also be deceived.' },
      { text: 'Add a 1-hour delay',                                          correct: false, rationale: 'Delays are often overridden for "urgent" requests, which is exactly the pattern BEC exploits.' },
    ],
  },
  {
    id: 'Q005',
    tacticId: 'T001',
    difficulty: 'easy',
    roles: ['analyst', 'executive'],
    question: 'Why is lookalike domain monitoring considered "high leverage" in F3 defense?',
    options: [
      { text: 'It generates the most alerts of any control',                                   correct: false, rationale: 'Quantity of alerts is not the goal.' },
      { text: 'It catches attacker infrastructure before it is used in an attack',             correct: true,  rationale: 'Domains are typically registered days before a phishing campaign. Monitoring gives you a proactive detection window at low cost.' },
      { text: 'It detects all phishing attempts',                                              correct: false, rationale: 'Many phishing attacks use legitimate compromised infrastructure, not lookalike domains.' },
      { text: 'It is required by FFIEC',                                                      correct: false, rationale: 'Regulatory status is not why the control is high-leverage.' },
    ],
  },
  {
    id: 'Q006',
    tacticId: 'T004',
    difficulty: 'medium',
    roles: ['soc', 'analyst'],
    question: 'Which of these is NOT a Defense Evasion technique in F3?',
    options: [
      { text: 'SIM swapping to defeat SMS MFA',                                 correct: false, rationale: 'This IS a Defense Evasion technique.' },
      { text: 'Device fingerprint spoofing',                                    correct: false, rationale: 'This IS a Defense Evasion technique.' },
      { text: 'Rapid layering of funds across mule accounts',                   correct: false, rationale: 'This IS Defense Evasion (specifically, evading transaction monitoring).' },
      { text: 'Purchasing stolen SSNs on a dark web marketplace',               correct: true,  rationale: 'That is a Resource Development activity, not Defense Evasion.' },
    ],
  },
  {
    id: 'Q007',
    tacticId: 'T005',
    difficulty: 'hard',
    roles: ['analyst', 'executive'],
    question: 'A pig butchering scheme involves an attacker building a romantic relationship with a victim over 3 months before convincing them to "invest" in a fake platform. Which F3 tactic best describes those 3 months?',
    options: [
      { text: 'Reconnaissance',                                   correct: false, rationale: 'Reconnaissance precedes contact with the target. The active relationship is not recon.' },
      { text: 'Resource Development',                             correct: false, rationale: 'The fake platform is the resource; the relationship is not a developed asset in the F3 sense.' },
      { text: 'Positioning',                                      correct: true,  rationale: 'Positioning captures the cultivation-of-trust phase that enables later execution. Pig butchering is the textbook example of why this tactic was added to F3.' },
      { text: 'Execution',                                        correct: false, rationale: 'Execution is the authorized transfer itself, which happens after the Positioning phase ends.' },
    ],
  },
  {
    id: 'Q008',
    tacticId: 'T007',
    difficulty: 'hard',
    roles: ['executive', 'soc'],
    question: 'From a governance standpoint, which capability most distinguishes institutions that recover fraud losses from those that do not?',
    options: [
      { text: 'A larger fraud investigation team',                                         correct: false, rationale: 'Team size alone does not drive recovery.' },
      { text: 'A pre-established, 24/7 interbank fraud coordination protocol with SWIFT gpi capability', correct: true, rationale: 'Recovery requires rapid coordination with the receiving bank within minutes. Institutions that build this muscle — with named contacts and clear escalation paths — recover at materially higher rates.' },
      { text: 'A higher fraud insurance limit',                                            correct: false, rationale: 'Insurance covers loss but is not a recovery capability.' },
      { text: 'Use of AI/ML transaction monitoring',                                       correct: false, rationale: 'ML detection helps prevent fraud but does not drive post-event recovery.' },
    ],
  },
]
