/**
 * Scenarios with branching decision support.
 *
 * Each stage has a stable `id`. Options may carry `leadsTo` pointing to a
 * consequence stage within the same scenario. If absent, the player advances
 * to the next primary stage in order.
 */

export const SCENARIOS = [
  {
    id: 'SC001',
    title: 'Business Email Compromise — CFO impersonation',
    severity: 'high',
    summary: 'Threat actor compromises the CFO\'s email and redirects a $2.3M vendor wire transfer to a mule account, then layers funds into cryptocurrency.',
    estimatedLoss: 2_300_000,
    roles: ['analyst', 'soc', 'executive'],
    stages: [
      {
        id: 'SC001-S1',
        order: 1,
        type: 'primary',
        techniqueId: 'F1067',
        heading: 'Reconnaissance — executive profiling',
        narrative: 'The attacker harvests LinkedIn profiles, press releases, and an SEC filing to identify the CFO, the company\'s top 5 vendors, and the typical monthly invoice cycle.',
        signals: [
          { severity: 'low',    text: 'Unusual OSINT activity on executive LinkedIn profiles' },
          { severity: 'medium', text: 'Lookalike domain registered — 3 characters different from trusted vendor' },
          { severity: 'high',   text: 'Spoofed vendor domain registered 3 days before typical invoice date' },
        ],
        question: 'Which control provides the highest leverage at the Reconnaissance stage?',
        options: [
          { text: 'Daily manual review of executive social media', correct: false, rationale: 'Manual monitoring does not scale and is inherently reactive.' },
          { text: 'Automated lookalike domain monitoring for your institution and top vendors', correct: true, rationale: 'Domain surveillance catches attacker infrastructure before it is used.' },
          { text: 'Restrict wire authorization to 2 named individuals', correct: false, rationale: 'Useful at Execution stage but addresses the wrong phase here.', leadsTo: 'SC001-S1C' },
          { text: 'Quarterly phishing awareness training for the CFO', correct: false, rationale: 'Awareness helps but is not the highest-leverage control at this phase.' },
        ],
      },
      {
        id: 'SC001-S1C',
        order: 1.5,
        type: 'consequence',
        techniqueId: 'F1067',
        heading: 'Consequence — the lookalike domain was never spotted',
        narrative: 'Three weeks later, the spoofed domain goes live. Your organization only discovers the fraud pattern during a post-incident review. By then, the attack has already moved well into Execution.',
        signals: [
          { severity: 'high', text: 'Fraud triage team asks: "Could this domain have been caught earlier?"' },
          { severity: 'medium', text: 'SOC discovers similar fraud affected 3 regional banks in the prior 90 days' },
        ],
        question: 'Given you are now catching up, what is the best next-step priority?',
        options: [
          { text: 'Roll out domain monitoring immediately AND accept that executive accounts need stronger safeguards', correct: true, rationale: 'Recovery starts by plugging both holes. Attackers are already positioned.' },
          { text: 'Focus only on training — awareness will catch the next one', correct: false, rationale: 'Training is useful but insufficient. Attackers are already past this stage.' },
          { text: 'Wait for the next budget cycle to deploy monitoring', correct: false, rationale: 'The threat is active now. Delayed response widens the window.' },
        ],
      },
      {
        id: 'SC001-S2',
        order: 2,
        type: 'primary',
        techniqueId: 'F1081',
        heading: 'Initial Access — phishing for credentials',
        narrative: 'A spear-phishing email from the spoofed vendor domain prompts the CFO\'s assistant to click a credential-harvesting link. Within hours, the attacker is logged into the CFO\'s email and has added a silent forwarding rule.',
        signals: [
          { severity: 'high', text: 'Mailbox login from new device + country change within 1 hour' },
          { severity: 'high', text: 'Silent email-forwarding rule added to CFO inbox' },
          { severity: 'medium', text: 'Assistant clicked link from domain registered 72 hours earlier' },
        ],
        question: 'Which control most directly prevents this initial access?',
        options: [
          { text: '90-day mandatory password rotation', correct: false, rationale: 'Rotation does not help when credentials are phished at the point of use.' },
          { text: 'Phishing-resistant MFA (FIDO2 hardware keys) on all executive accounts', correct: true, rationale: 'FIDO2 is resistant to real-time phishing; the attacker cannot replay a hardware-backed assertion.' },
          { text: 'Block all external email', correct: false, rationale: 'Impractical and does not address the underlying technique.' },
          { text: 'Quarterly security awareness training', correct: false, rationale: 'Complements but does not replace a technical control at this stage.', leadsTo: 'SC001-S2C' },
        ],
      },
      {
        id: 'SC001-S2C',
        order: 2.5,
        type: 'consequence',
        techniqueId: 'F1081',
        heading: 'Consequence — credentials compromised, no FIDO2',
        narrative: 'Without phishing-resistant MFA, the attacker is inside the CFO\'s mailbox within hours of the phish. They have added mail-forwarding rules, started reading months of vendor correspondence, and are pattern-matching invoice timing.',
        signals: [
          { severity: 'high', text: 'Attacker has weeks of dwell time studying invoice patterns' },
          { severity: 'high', text: 'All inbound CFO email being silently copied to an external drop' },
        ],
        question: 'Detection & response is now your best lever. What most reliably surfaces this intrusion?',
        options: [
          { text: 'Alert on inbox rule creation that forwards externally for executive accounts', correct: true, rationale: 'Rule-creation events are logged. A targeted alert on executive mailboxes is low-noise and high-signal.' },
          { text: 'Weekly manual review of mailbox rules', correct: false, rationale: 'Manual process runs on a cadence the attacker will outpace.' },
          { text: 'Block all mail-forwarding rules', correct: false, rationale: 'Too blunt; legitimate business uses exist.' },
        ],
      },
      {
        id: 'SC001-S3',
        order: 3,
        type: 'primary',
        techniqueId: 'F1038',
        heading: 'Execution — fraudulent bank transfer',
        narrative: 'The attacker, now in control of the CFO\'s email, emails accounts payable with an "urgent confidential acquisition" and instructs a $2.3M wire to a new beneficiary. Urgency framing is used to suppress normal verification.',
        signals: [
          { severity: 'high', text: 'Wire request bypasses normal 2-person approval chain' },
          { severity: 'high', text: 'Urgency and confidentiality language in the email' },
          { severity: 'medium', text: 'Destination account is a new beneficiary' },
        ],
        question: 'Which process control would stop the wire?',
        options: [
          { text: 'Out-of-band voice verification via a pre-established phone number for all wires over $100k', correct: true, rationale: 'Out-of-band verification defeats BEC entirely — the attacker cannot intercept a separate channel.' },
          { text: '24-hour delay on all wires', correct: false, rationale: 'Delays are routinely overridden for "urgent" transactions.' },
          { text: 'Require CFO to personally approve wires in the banking portal', correct: false, rationale: 'The email is compromised — the CFO\'s "approval" is coming from the attacker.', leadsTo: 'SC001-S3C' },
          { text: 'Flag wires over $500k for compliance review', correct: false, rationale: 'Helpful but can be defeated by sophisticated social engineering.' },
        ],
      },
      {
        id: 'SC001-S3C',
        order: 3.5,
        type: 'consequence',
        techniqueId: 'F1038',
        heading: 'Consequence — the wire executed',
        narrative: 'The $2.3M wire settled 14 hours ago. Funds were split across 5 accounts within 6 hours and 40% was converted to crypto at an offshore exchange. You now run Monetization response, not prevention.',
        signals: [
          { severity: 'high', text: 'Funds split across 5+ accounts within 6 hours' },
          { severity: 'high', text: 'Crypto conversion detected at receiving institution' },
        ],
        question: 'What action maximizes partial recovery now?',
        options: [
          { text: 'Initiate SWIFT gpi recall and directly contact each receiving bank\'s fraud team within the first hour', correct: true, rationale: 'Direct interbank coordination works when layering has not completed. Every hour matters.' },
          { text: 'File a SAR with FinCEN and wait for guidance', correct: false, rationale: 'SARs are mandatory but slow. Recovery is time-sensitive.' },
          { text: 'Escalate to the CEO for decision on next steps', correct: false, rationale: 'Executive escalation in the first hour costs precious recovery window.' },
        ],
      },
      {
        id: 'SC001-S4',
        order: 4,
        type: 'primary',
        techniqueId: 'F1047',
        heading: 'Monetization — cashout to cryptocurrency',
        narrative: 'Funds land in a domestic mule account, are split across 5 accounts within 6 hours, and 40% is converted to Bitcoin at an offshore exchange within 48 hours.',
        signals: [
          { severity: 'high', text: 'Funds split across 5+ accounts within 6 hours of receipt' },
          { severity: 'high', text: 'Crypto conversion detected at receiving institution' },
          { severity: 'medium', text: 'Mule account was opened 14 days prior with minimal history' },
        ],
        question: 'Which response action maximizes fund recovery?',
        options: [
          { text: 'File a SAR with FinCEN and wait for guidance', correct: false, rationale: 'SARs are mandatory but slow. Recovery is time-sensitive.' },
          { text: 'Initiate SWIFT gpi recall and directly contact the receiving bank\'s fraud team within the first hour', correct: true, rationale: 'The first 60 minutes determine recovery rate.' },
          { text: 'Launch an internal investigation before acting', correct: false, rationale: 'Every hour reduces recovery probability significantly.' },
          { text: 'Alert law enforcement and take no other action', correct: false, rationale: 'Law enforcement is important but slow.' },
        ],
      },
    ],
  },

  {
    id: 'SC002',
    title: 'Synthetic Identity — 18-month bust-out',
    severity: 'high',
    summary: 'A fraud ring builds 12 synthetic identities over 18 months, cultivates credit history on each, then busts out all accounts simultaneously for $850k.',
    estimatedLoss: 850_000,
    roles: ['analyst', 'executive', 'teller'],
    stages: [
      {
        id: 'SC002-S1',
        order: 1,
        type: 'primary',
        techniqueId: 'F1062',
        heading: 'Resource Development — fake identity documents',
        narrative: 'The ring purchases unused SSNs (belonging to children) from a dark web market and combines them with fabricated names, addresses, and employment records, plus fake supporting documents.',
        signals: [
          { severity: 'medium', text: 'SSN issuance date inconsistent with claimed birth year' },
          { severity: 'medium', text: 'Thin credit file with no historical tradelines' },
          { severity: 'high', text: 'Same address appears on 12+ recent applications at your bank' },
        ],
        question: 'Which onboarding control most reliably detects synthetic identities?',
        options: [
          { text: 'Standard CIP (Customer Identification Program) checks', correct: false, rationale: 'CIP validates SSNs but does not detect synthetic combinations.', leadsTo: 'SC002-S1C' },
          { text: 'SSN-age-vs-birthyear cross-referencing plus cross-institution application velocity', correct: true, rationale: 'Synthetic IDs show SSN age mismatches or appear at many institutions in short windows.' },
          { text: 'Mandatory in-person identity verification for all new accounts', correct: false, rationale: 'Helpful but defeated by high-quality fabricated IDs.' },
          { text: 'Cap all new account credit lines at $1,000', correct: false, rationale: 'Punishes legitimate customers and does not prevent the eventual bust-out.' },
        ],
      },
      {
        id: 'SC002-S1C',
        order: 1.5,
        type: 'consequence',
        techniqueId: 'F1062',
        heading: 'Consequence — synthetics onboarded undetected',
        narrative: 'Standard CIP passed every identity. All 12 accounts are now open and beginning their cultivation phase. You have 12-18 months before the bust-out — but you will not know which accounts are synthetic until then.',
        signals: [
          { severity: 'medium', text: 'Accounts behave "too perfectly" — but by design' },
          { severity: 'low', text: 'Fraud team flags cluster only after pattern emerges' },
        ],
        question: 'You cannot undo onboarding. What behavioral monitoring catches this next?',
        options: [
          { text: 'Graph clustering on shared application attributes across the portfolio', correct: true, rationale: 'The ring reuses devices, addresses, or phone fragments. Graph analytics surface the cluster even after onboarding.' },
          { text: 'Strict minimum balance requirements', correct: false, rationale: 'Does not detect synthetics — hurts legitimate customers.' },
          { text: 'Wait for first delinquency to flag', correct: false, rationale: 'Bust-out rings rarely become delinquent before the coordinated attack.' },
        ],
      },
      {
        id: 'SC002-S2',
        order: 2,
        type: 'primary',
        techniqueId: 'F1008',
        heading: 'Positioning — account manipulation over time',
        narrative: 'For 12 to 18 months the ring makes small on-time payments on each account and gradually modifies account settings (credit limit increases, beneficiary additions) to prepare for the bust-out. This is the Positioning tactic unique to F3.',
        signals: [
          { severity: 'low', text: 'Pattern-perfect payment behavior across all accounts' },
          { severity: 'medium', text: 'Multiple credit limit increase requests in short windows' },
          { severity: 'high', text: 'Similar account lifecycle pattern across 8 accounts in same region' },
        ],
        question: 'The Positioning tactic is unique to F3. What is the key risk management implication?',
        options: [
          { text: 'Fraud rings can operate undetected for over a year before the attack', correct: true, rationale: 'Positioning means point-in-time fraud scoring fails. Behavioral analytics over the account lifecycle are essential.' },
          { text: 'Credit limit increases should be automatically denied', correct: false, rationale: 'Blanket denials harm legitimate customers.' },
          { text: 'Fraud only occurs at account opening', correct: false, rationale: 'Positioning captures fraud that matures well after account opening.' },
          { text: 'On-time payments always indicate a legitimate account', correct: false, rationale: 'The Positioning tactic shows fraudsters mimic this behavior.' },
        ],
      },
      {
        id: 'SC002-S3',
        order: 3,
        type: 'primary',
        techniqueId: 'F1048',
        heading: 'Execution — coordinated fraudulent purchasing',
        narrative: 'On a single business day, the ring simultaneously maxes out all 12 accounts via cash advances and large purchases, then abandons the identities. Total loss: $850k across 4 institutions.',
        signals: [
          { severity: 'high', text: 'Simultaneous max utilization across 8+ accounts in 48 hours' },
          { severity: 'high', text: 'All accounts become delinquent on the same billing cycle' },
          { severity: 'high', text: 'Cash advance and purchase pattern across multiple linked accounts within 24 hours' },
        ],
        question: 'What analytics capability best detects coordinated bust-outs in progress?',
        options: [
          { text: 'Individual account utilization alerts', correct: false, rationale: 'By design, no single account looks unusual — it is the correlation that matters.' },
          { text: 'Graph analytics linking accounts by shared attributes (address, device, application metadata)', correct: true, rationale: 'The ring shares operational attributes across all synthetic identities. Graph detection reveals the cluster in real time.' },
          { text: 'Raising minimum payment requirements portfolio-wide', correct: false, rationale: 'Loss mitigation, not detection.' },
          { text: 'Manual freezing after delinquency is reported', correct: false, rationale: 'Too late — losses have already occurred.' },
        ],
      },
    ],
  },

  {
    id: 'SC003',
    title: 'SIM Swap — customer account takeover',
    severity: 'medium',
    summary: 'Attacker uses breached PII to execute a SIM swap at the mobile carrier, intercepts SMS MFA codes, and drains $180k from the victim\'s investment account.',
    estimatedLoss: 180_000,
    roles: ['analyst', 'teller', 'soc'],
    stages: [
      {
        id: 'SC003-S1',
        order: 1,
        type: 'primary',
        techniqueId: 'F1067',
        heading: 'Reconnaissance — gathering victim information',
        narrative: 'The attacker purchases the customer\'s full identity bundle (name, address, DOB, last four SSN, phone number) from a dark web marketplace and verifies high account balance via social media.',
        signals: [
          { severity: 'low', text: 'Customer PII present in recent breach databases' },
          { severity: 'low', text: 'Customer publicly discusses investment account on social media' },
        ],
        question: 'What proactive control addresses this stage best?',
        options: [
          { text: 'Continuous dark web monitoring for your customers\' exposed credentials, paired with proactive step-up authentication on high-risk accounts', correct: true, rationale: 'You cannot stop breaches at other companies — but you can detect exposure and raise the bar preemptively.' },
          { text: 'Quarterly customer password rotation', correct: false, rationale: 'The attacker has PII, not passwords. Rotation does not help.' },
          { text: 'Block SMS authentication entirely', correct: false, rationale: 'Blunt and harms customers.' },
          { text: 'Increase the minimum account balance requirement', correct: false, rationale: 'Irrelevant to the information exposure risk.' },
        ],
      },
      {
        id: 'SC003-S2',
        order: 2,
        type: 'primary',
        techniqueId: 'T1451',
        heading: 'Initial Access — SIM card swap',
        narrative: 'Using stolen PII, the attacker social-engineers the mobile carrier into porting the victim\'s number to a new SIM. SMS-based MFA codes now flow to the attacker.',
        signals: [
          { severity: 'high', text: 'Telecom partner reports SIM port event on customer\'s number' },
          { severity: 'high', text: 'SMS delivery failure for customer notifications' },
          { severity: 'medium', text: 'Customer device fingerprint changes suddenly' },
        ],
        question: 'Which control most directly addresses SIM swap attacks?',
        options: [
          { text: 'Require customers to verify recent transactions when calling support', correct: false, rationale: 'The swap happens at the carrier, not the bank\'s phone channel.' },
          { text: 'Real-time SIM swap detection via telecom API partnerships, triggering mandatory step-up authentication', correct: true, rationale: 'Telecom APIs expose SIM port events. Using them as a step-up trigger closes the window.' },
          { text: 'Require SMS OTP for all transactions', correct: false, rationale: 'SMS OTP is exactly what SIM swapping defeats.', leadsTo: 'SC003-S2C' },
          { text: 'Mandate biometric authentication inside the mobile app', correct: false, rationale: 'Useful but the attacker can trigger SMS-based password resets that bypass the app.' },
        ],
      },
      {
        id: 'SC003-S2C',
        order: 2.5,
        type: 'consequence',
        techniqueId: 'T1451',
        heading: 'Consequence — SMS OTP intercepted, account drained',
        narrative: 'Attacker triggered a password reset via SMS, captured the OTP, and initiated a $180k wire from the victim\'s investment account. The transfer is already in flight.',
        signals: [
          { severity: 'high', text: 'Wire initiated to a brand-new beneficiary minutes after device change' },
          { severity: 'high', text: 'Customer not reachable by phone (SIM is in attacker\'s hands)' },
        ],
        question: 'What limits the damage in the next 30 minutes?',
        options: [
          { text: 'Pause the outbound wire and reach the customer via a verified secondary channel (email, branch)', correct: true, rationale: 'When the primary channel is compromised, you validate through a separate, pre-established channel.' },
          { text: 'Let the wire complete and pursue recovery later', correct: false, rationale: 'Delay the wire — recovery once funds clear is much harder.' },
          { text: 'Send an SMS asking the customer to confirm', correct: false, rationale: 'The SMS goes straight to the attacker.' },
        ],
      },
    ],
  },
]
