export const SCENARIOS = [
  {
    id: 'SC001',
    title: 'Business Email Compromise — CFO impersonation',
    severity: 'high',
    summary: 'Threat actor compromises the CFO\'s email and redirects a $2.3M vendor wire transfer to a mule account, then layers funds into cryptocurrency.',
    estimatedLoss: 2_300_000,
    roles: ['analyst', 'soc', 'executive'],
    stages: [
      {
        order: 1,
        techniqueId: 'T001.001',
        heading: 'Reconnaissance — executive profiling',
        narrative: 'The attacker harvests LinkedIn profiles, press releases, and an SEC filing to identify the CFO, the company\'s top 5 vendors, and the typical monthly invoice cycle.',
        signals: [
          { severity: 'low',    text: 'Unusual OSINT activity on executive LinkedIn profiles' },
          { severity: 'medium', text: 'Lookalike domain registered — 3 characters different from trusted vendor' },
          { severity: 'high',   text: 'Spoofed vendor domain registered 3 days before typical invoice date' },
        ],
        question: 'Which control provides the highest leverage at the Reconnaissance stage?',
        options: [
          { text: 'Daily manual review of executive social media',                                          correct: false, rationale: 'Manual monitoring does not scale and is inherently reactive.' },
          { text: 'Automated lookalike domain monitoring for your institution and top vendors',             correct: true,  rationale: 'Domain surveillance catches attacker infrastructure before it is used. Cost per alert is low; leverage is high.' },
          { text: 'Restrict wire authorization to 2 named individuals',                                     correct: false, rationale: 'Useful at Execution stage but addresses the wrong phase here.' },
          { text: 'Quarterly phishing awareness training for the CFO',                                      correct: false, rationale: 'Awareness helps but is not the highest-leverage control at this phase.' },
        ],
      },
      {
        order: 2,
        techniqueId: 'T003.001',
        heading: 'Initial Access — spear phishing',
        narrative: 'A spear-phishing email from the spoofed vendor domain prompts the CFO\'s assistant to click a credential-harvesting link. Within hours, the attacker is logged into the CFO\'s email and has added a silent forwarding rule.',
        signals: [
          { severity: 'high',   text: 'Mailbox login from new device + country change within 1 hour' },
          { severity: 'high',   text: 'Silent email-forwarding rule added to CFO inbox' },
          { severity: 'medium', text: 'Assistant clicked link from domain registered 72 hours earlier' },
        ],
        question: 'Which control most directly prevents this initial access?',
        options: [
          { text: '90-day mandatory password rotation',                                                     correct: false, rationale: 'Rotation does not help when credentials are phished at the point of use.' },
          { text: 'Phishing-resistant MFA (FIDO2 hardware keys) on all executive accounts',                 correct: true,  rationale: 'FIDO2 is resistant to real-time phishing; the attacker cannot replay a hardware-backed assertion.' },
          { text: 'Block all external email',                                                               correct: false, rationale: 'Impractical and does not address the underlying technique.' },
          { text: 'Quarterly security awareness training',                                                  correct: false, rationale: 'Complements but does not replace a technical control at this stage.' },
        ],
      },
      {
        order: 3,
        techniqueId: 'T006.001',
        heading: 'Execution — fraudulent wire request',
        narrative: 'The attacker, now in control of the CFO\'s email, emails accounts payable with an "urgent confidential acquisition" and instructs a $2.3M wire to a new beneficiary. Urgency framing is used to suppress normal verification.',
        signals: [
          { severity: 'high',   text: 'Wire request bypasses normal 2-person approval chain' },
          { severity: 'high',   text: 'Urgency and confidentiality language in the email' },
          { severity: 'medium', text: 'Destination account is a new beneficiary' },
        ],
        question: 'Which process control would stop the wire?',
        options: [
          { text: 'Out-of-band voice verification via a pre-established phone number for all wires over $100k', correct: true,  rationale: 'Out-of-band verification defeats BEC entirely — the attacker cannot intercept a separate channel.' },
          { text: '24-hour delay on all wires',                                                              correct: false, rationale: 'Delays are routinely overridden for "urgent" transactions.' },
          { text: 'Require CFO to personally approve wires in the banking portal',                           correct: false, rationale: 'The email is compromised — the CFO\'s "approval" is coming from the attacker.' },
          { text: 'Flag wires over $500k for compliance review',                                             correct: false, rationale: 'Helpful but can be defeated by sophisticated social engineering of the reviewer.' },
        ],
      },
      {
        order: 4,
        techniqueId: 'T007.001',
        heading: 'Monetization — crypto conversion',
        narrative: 'Funds land in a domestic mule account, are split across 5 accounts within 6 hours, and 40% is converted to Bitcoin at an offshore exchange within 48 hours.',
        signals: [
          { severity: 'high',   text: 'Funds split across 5+ accounts within 6 hours of receipt' },
          { severity: 'high',   text: 'Crypto conversion detected at receiving institution' },
          { severity: 'medium', text: 'Mule account was opened 14 days prior with minimal history' },
        ],
        question: 'Which response action maximizes fund recovery?',
        options: [
          { text: 'File a SAR with FinCEN and wait for guidance',                                           correct: false, rationale: 'SARs are mandatory but slow. Recovery is time-sensitive.' },
          { text: 'Initiate SWIFT gpi recall and directly contact the receiving bank\'s fraud team within the first hour', correct: true, rationale: 'The first 60 minutes determine recovery rate. Direct bank-to-bank coordination works when layering has not completed.' },
          { text: 'Launch an internal investigation before acting',                                         correct: false, rationale: 'Every hour reduces recovery probability significantly.' },
          { text: 'Alert law enforcement and take no other action',                                         correct: false, rationale: 'Law enforcement involvement is essential but must run in parallel with recall, not replace it.' },
        ],
      },
    ],
  },

  {
    id: 'SC002',
    title: 'Synthetic Identity — 18-month bust-out',
    severity: 'high',
    summary: 'A fraud ring builds 12 synthetic identities over 18 months, cultivates credit history on each, then busts out all accounts simultaneously for $850k.',
    estimatedLoss: 850_000,
    roles: ['analyst', 'executive', 'teller'],
    stages: [
      {
        order: 1,
        techniqueId: 'T002.002',
        heading: 'Resource Development — synthetic identity creation',
        narrative: 'The ring purchases unused SSNs (belonging to children) from a dark web market and combines them with fabricated names, addresses, and employment records. Each identity is used to apply at 6 different institutions.',
        signals: [
          { severity: 'medium', text: 'SSN issuance date inconsistent with claimed birth year' },
          { severity: 'medium', text: 'Thin credit file with no historical tradelines' },
          { severity: 'high',   text: 'Same address appears on 12+ recent applications at your bank' },
        ],
        question: 'Which onboarding control most reliably detects synthetic identities?',
        options: [
          { text: 'Standard CIP (Customer Identification Program) checks',                                correct: false, rationale: 'CIP validates SSNs but does not detect synthetic combinations.' },
          { text: 'SSN-age-vs-birthyear cross-referencing plus cross-institution application velocity',   correct: true,  rationale: 'Synthetic IDs reliably show either SSN age mismatches or appear at many institutions in short windows. Both signals are operationally cheap to compute.' },
          { text: 'Mandatory in-person identity verification for all new accounts',                       correct: false, rationale: 'Helpful but defeated by high-quality fabricated IDs and poorly scalable.' },
          { text: 'Cap all new account credit lines at $1,000',                                           correct: false, rationale: 'Punishes legitimate customers and does not prevent the eventual bust-out.' },
        ],
      },
      {
        order: 2,
        techniqueId: 'T005.001',
        heading: 'Positioning — credit history cultivation',
        narrative: 'For 12–18 months the ring makes small on-time payments on each account, requests gradual credit limit increases, and never triggers any single-account fraud signal. This is the Positioning tactic unique to F3.',
        signals: [
          { severity: 'low',    text: 'Pattern-perfect payment behavior across all accounts' },
          { severity: 'medium', text: 'Multiple credit limit increase requests in short windows' },
          { severity: 'high',   text: 'Similar account lifecycle pattern across 8 accounts in same branch region' },
        ],
        question: 'Why does the Positioning tactic matter so much for executive risk strategy?',
        options: [
          { text: 'Because it shows traditional point-in-time fraud scoring will systematically miss these cases', correct: true,  rationale: 'Positioning is specifically about mimicking legitimate behavior over long windows. Only portfolio-level behavioral analytics over time can catch it.' },
          { text: 'Because it means all credit limit increase requests should be denied',                 correct: false, rationale: 'Blanket denial harms good customers and does not solve the problem.' },
          { text: 'Because fraud only occurs at account opening',                                         correct: false, rationale: 'Positioning is the opposite — fraud matures months after opening.' },
          { text: 'Because on-time payments always indicate legitimacy',                                  correct: false, rationale: 'The Positioning tactic explicitly describes fraudsters mimicking this behavior.' },
        ],
      },
      {
        order: 3,
        techniqueId: 'T006.003',
        heading: 'Execution — coordinated bust-out',
        narrative: 'On a single business day, the ring simultaneously maxes out all 12 accounts, takes cash advances at the daily limit, and abandons the identities. Total loss: $850k across 4 institutions.',
        signals: [
          { severity: 'high', text: 'Simultaneous max utilization across 8+ accounts in 48 hours' },
          { severity: 'high', text: 'All accounts become delinquent on the same billing cycle' },
          { severity: 'high', text: 'Cash advance pattern across multiple linked accounts within 24 hours' },
        ],
        question: 'Which analytics capability best detects coordinated bust-outs in progress?',
        options: [
          { text: 'Individual account utilization alerts',                                                correct: false, rationale: 'By design, no single account looks unusual — it is the correlation that matters.' },
          { text: 'Graph analytics linking accounts by shared attributes (address, device, application metadata)', correct: true, rationale: 'The ring shares operational attributes across all synthetic identities. Graph detection reveals the cluster in real time.' },
          { text: 'Raising minimum payment requirements portfolio-wide',                                  correct: false, rationale: 'Loss mitigation, not detection.' },
          { text: 'Manual freezing after delinquency is reported',                                        correct: false, rationale: 'Too late — losses have already occurred.' },
        ],
      },
    ],
  },

  {
    id: 'SC003',
    title: 'SIM Swap — customer account takeover',
    severity: 'medium',
    summary: 'Attacker uses breached PII to execute a SIM swap at the mobile carrier, intercepts SMS MFA codes, and drains $180k from the victim\'s investment account.',
    estimatedLoss: 180_000,
    roles: ['analyst', 'teller', 'soc'],
    stages: [
      {
        order: 1,
        techniqueId: 'T001.003',
        heading: 'Reconnaissance — PII acquisition',
        narrative: 'The attacker purchases the customer\'s full identity bundle (name, address, DOB, last four SSN, phone number) from a dark web marketplace and verifies high account balance via social media posts.',
        signals: [
          { severity: 'low',    text: 'Customer PII present in recent breach databases' },
          { severity: 'low',    text: 'Customer publicly discusses investment account on social media' },
        ],
        question: 'What proactive control addresses this stage best?',
        options: [
          { text: 'Continuous dark web monitoring for your customers\' exposed credentials, paired with proactive step-up authentication on high-risk accounts', correct: true, rationale: 'You cannot stop breaches at other companies — but you can detect exposure and raise the bar preemptively for those customers.' },
          { text: 'Quarterly customer password rotation',                                                 correct: false, rationale: 'The attacker has PII, not passwords. Rotation does not help here.' },
          { text: 'Block SMS authentication entirely',                                                    correct: false, rationale: 'Blunt and harms customers. Better to upgrade high-risk accounts to phishing-resistant MFA.' },
          { text: 'Increase the minimum account balance requirement',                                     correct: false, rationale: 'Irrelevant to the information exposure risk.' },
        ],
      },
      {
        order: 2,
        techniqueId: 'T003.003',
        heading: 'Initial Access — SIM swap executed',
        narrative: 'Using stolen PII, the attacker social-engineers the mobile carrier into porting the victim\'s number to a new SIM. SMS-based MFA codes now flow to the attacker. The bank sees a sudden device change on the customer\'s account.',
        signals: [
          { severity: 'high',   text: 'Telecom partner reports SIM port event on customer\'s number' },
          { severity: 'high',   text: 'SMS delivery failure for customer notifications' },
          { severity: 'medium', text: 'Customer device fingerprint changes suddenly' },
        ],
        question: 'SIM swap is a Defense Evasion technique. Which control most directly addresses it?',
        options: [
          { text: 'Real-time SIM swap detection via telecom API partnerships, triggering mandatory step-up authentication', correct: true, rationale: 'Telecom APIs (available from all major US carriers) expose SIM port events. Using them as a step-up trigger closes the evasion window.' },
          { text: 'Require customers to verify a recent transaction when calling support',                correct: false, rationale: 'The evasion happens at the carrier, not the bank\'s phone channel.' },
          { text: 'Require SMS OTP for all transactions',                                                 correct: false, rationale: 'SMS OTP is exactly what the SIM swap is designed to defeat.' },
          { text: 'Mandate biometric authentication inside the mobile app',                              correct: false, rationale: 'Useful but the attacker can trigger SMS-based password resets that bypass the app entirely.' },
        ],
      },
    ],
  },
]
